# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio of Topher Young
email: topher@hellotopher.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Topher Young and I am a web designer & developer who specializes in creating highly usable, unique, and captivating interactive applications and products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hellotopher.com" # the base hostname & protocol for your site
github_username:  topheryoung
subhead: "Designer & Developer"

# Build settings
markdown: kramdown
